export default {
  login: 'Benai Kumar',
  id: 42133389,
  node_id: 'MDQ6VXNlcjQyMTMzMzg5',
  // avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
  avatar_url: 'https://avatars.githubusercontent.com/u/42668661?v=4',
  gravatar_id: '',
  // url: 'https://api.github.com/users/john-smilga',
  url: '  https://github.com/benai9916',
  html_url: 'https://github.com/benai',
  followers_url: 'https://github.com/benai9916?tab=followers',
  following_url: 'https://github.com/benai9916?tab=following',
  gists_url: 'https://api.github.com/users/benai/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/benai/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
  organizations_url: 'https://api.github.com/users/john-smilga/orgs',
  repos_url: 'https://github.com/benai9916?tab=repositories',
  events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/john-smilga/received_events',
  type: 'User',
  site_admin: false,
  name: 'Benai Kumar',
  company: 'Shiroest',
  blog: 'https://medium.com/next-gen-machine-learning/interactive-covid-19-analysis-dashboard-with-dash-c0da1008b00',
  location: 'Bangalore',
  email: null,
  hireable: null,
  bio: 'Creator of Shiroest',
  twitter_username: 'KumarBenai',
  public_repos: 66,
  public_gists: 0,
  followers: 8,
  following: 3,
  created_at: '2018-08-06T06:48:23Z',
  updated_at: '2020-07-08T05:01:32Z',
}
